{{- if .Values.backend.enabled }}
{{- if not .Values.backend.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guestbook.fullname" . }}-redis
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  password: {{ .Values.backend.auth.password | quote }}
{{- end }}
{{- end }}
