{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guestbook.fullname" . }}-redis
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "guestbook.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "guestbook.backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command:
            - redis-server
            - --requirepass
            - $(REDIS_PASSWORD)
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.backend.auth.existingSecret }}{{ .Values.backend.auth.existingSecret }}{{ else }}{{ include "guestbook.fullname" . }}-redis{{ end }}
                  key: password
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli -a "$REDIS_PASSWORD" ping
            initialDelaySeconds: 5
{{- end }}
